### ISSUE TITLE
incorrect output 

### ISSUE THREAD

**Issue by jianshu93** [cgoliver/Nussinov#2]
GGGAAAUCC as input it is wrong, should have 3 matches. GGA and UCC

**Comment by cgoliver** [comment]
Hi @jianshu93 ! Thanks for the feedback! May I ask what value you used for `min_loop_length`? The innermost AU pair in your example would be less than the deafult `4` minimum loop length and so there would be no pair formed.

**Comment by cgoliver** [comment]
If you change the value of `min_loop_length` to `2` you get the result you were expecting:

```
> python nuss.py "GGGAAAUCC"
('((.(..)))', [(0, 8), (1, 7), (3, 6)])
```

**Comment by jianshu93** [comment]
thank you problem solved!
